version: "2"

services:
  app:
    image: yulapshun/telegram-hihibot:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/root
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    command: python main.py
